import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/languagedropdown">LanguageDropdown</Link>
        </li>
        <li>
          <Link to="/myprofiledropdown">MyprofileDropdown</Link>
        </li>
        <li>
          <Link to="/paymentnotification">PaymentNotification</Link>
        </li>
        <li>
          <Link to="/pickupconformation">Pickupconformation</Link>
        </li>
        <li>
          <Link to="/bookingconformation">Bookingconformation</Link>
        </li>
        <li>
          <Link to="/passwordreset">Passwordreset</Link>
        </li>
        <li>
          <Link to="/ridesview">Ridesview</Link>
        </li>
        <li>
          <Link to="/ridesviewone">RidesviewOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
